name: Checkout and build
on:
  workflow_dispatch:
jobs:
  build:
    name: Checkout and build 
    runs-on: ubuntu-latest
    steps:
      ### TEST ONE
      - uses: actions/checkout@v4
        with:
          steps:
            - run: echo Step1
              
         
