name: Checkout and build
on:
  workflow_dispatch:
jobs:
  s-c-function:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Code
        run: echo s-c-function
  s-c-stream:
    runs-on: ubuntu-latest
    steps:
      - name: Test Code
        run: echo s-c-stream
              
         
