name: Orchestrate with wait
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Orchestrate Cloud Build
    runs-on: ubuntu-latest
    steps:
      - name: Build test-one
        run: |
          echo "Build test-one"
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: olegz
          repo: test-one
          github_token: ${{ secrets.RELEASE_TOKEN }} 
          workflow_file_name: maven.yml
      - name: Build test-two
        run: |
          echo "Build test-two"
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: olegz
          repo: test-two
          github_token: ${{ secrets.RELEASE_TOKEN }} 
          workflow_file_name: maven.yml
      - name: Next Step
        run: |
          echo "Running nexet step"
