name: Checkout and build
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
jobs:
  #BUILD
  spring-cloud-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: spring-cloud/spring-cloud-build
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven build of spring-cloud-build
        run: mvn -B package --file pom.xml
  #FUNCTION
  spring-cloud-function:
    needs: spring-cloud-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: spring-cloud/spring-cloud-function
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven build of spring-cloud-build
        run: mvn -B package --file pom.xml
  #STREAM      
  spring-cloud-stream:
    needs: spring-cloud-function
    uses: olegz/publisher/.github/workflows/spring-cloud-stream-build.yml@main
  #COMMONS
  spring-cloud-commons:
    needs: spring-cloud-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: spring-cloud/spring-cloud-commons
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven build of spring-cloud-build
        run: mvn -B package --file pom.xml
  #TASK
  spring-cloud-task:
    needs: [spring-cloud-build, spring-cloud-function, spring-cloud-commons]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: olegz/test-one
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven build of spring-cloud-build
        run: mvn -B package --file pom.xml
