name: Spring Cloud Build
on:
  push:
    branches: [main]
  workflow_dispatch: 
jobs:
  receiver:
      runs-on: ubuntu-latest
      steps:
        - name: A event received 1
          run: |
            echo "Event received1" 
        - name: A event received 2
          run: |
            echo "Event received2" 
