


name: Test ACTION from JSON

on:
  workflow_dispatch:
  
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      ENVSETTINGS: ${{ steps.setMyEnv.outputs.MY_OBJECT }}
    steps:
     - id: setMyEnv
       run: |
          echo 'MY_OBJECT={ "A_SECOND_VAR": "Hello", "A_THIRD_VAR": "Hello again" }' >> $GITHUB_OUTPUT
  print:
    needs: [ configure ]
    runs-on: ubuntu-latest
    env: ${{ fromJson(needs.myjob.outputs.ENVSETTINGS) }}
    steps:
      - name: Show the value
        run: |
          echo $A_SECOND_VAR
        
