


name: Test ACTION from JSON

on:
  workflow_dispatch:
  
jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      ENVSETTINGS: ${{ steps.setMyEnv.outputs.MY_OBJECT }}
    steps:
     - id: setMyEnv
       #run: echo 'MY_OBJECT=$(jq -c . < ./cloud.json)' >> $GITHUB_OUTPUT
       run: echo 'MY_OBJECT=$(cat ./cloud.json)' >> $GITHUB_OUTPUT
     - id: hjk
       run: echo ${ENVSETTINGS}
       #run: |
          #echo 'MY_OBJECT={ "BOOT_VERSION": "4.0.0", "CLOUD_VERSION": "4.5.4" }' >> $GITHUB_OUTPUT
  print:
    needs: [ configure ]
    runs-on: ubuntu-latest
    env: ${{ fromJson(needs.configure.outputs.ENVSETTINGS) }}
    steps:
      - name: Show the value
        run: |
          echo $BOOT_VERSION
        
