name: Test ACTION

on:
  workflow_dispatch:
  
jobs:
  testJob:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
          cat test.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - run: |
          echo '${{ fromJson(env.PACKAGE_JSON).version }}'
