name: Test ACTION

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: "./"

    - name: get properties
      id: json_properties
      uses: ./
      with: 
        file_path: 'test.json'

    - run: |
        echo ${{steps.json_properties.outputs.cloud-version}}
        echo ${{steps.json_properties.outputs.boot-version}}
        echo ${{steps.json_properties.outputs.stream-version}}
        
    


